 <function_name> ::= alphaFunc | betaFunc | gammaFunc | deltaFunc | epsilonFunc | zetaFunc | etaFunc | thetaFunc | iotaFunc | kappaFunc | lambdaFunc | muFunc | nuFunc | xiFunc | omicronFunc | piFunc | rhoFunc | sigmaFunc | tauFunc | upsilonFunc | phiFunc | chiFunc | psiFunc | omegaFunc