import httpx

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 8008
COVERAGE_SERVER_URL = "http://localhost:8001"
SEED_DIR = "seeds"
REQUEST_TIMEOUT=httpx.Timeout(12000)


SERVER_HOST_COMPILER_TEST = "0.0.0.0"
SERVER_PORT_COMPILER_TEST = 8028
COMPILER_TEST_SERVER_URL = "http://localhost:5060"
SEED_DIR_COMPILER_TEST = "seeds_compilation_test"
REQUEST_TIMEOUT_COMPILER_TEST=httpx.Timeout(50000)


SERVER_HOST_PLUGIN_CRASH_TEST = "0.0.0.0"
SERVER_PORT_PLUGIN_CRASH_TEST = 8128
PLUGIN_CRASH_TEST_SERVER_URL = "http://localhost:8101"
SEED_DIR_PLUGIN_CRASH = "seeds_plugin_crash_test"
REQUEST_TIMEOUT_PLUGIN_CRASH_TEST=httpx.Timeout(12000)