[PATHS]
grammar_path = Grammar/Program_Constructs
template_path=Program_Templates
output_path=Output
ast_json_output=Output/AST/Json
ast_diagrams_output=Output/AST/Diagram


[PROGRAM_GENERATION]
build_a_random_template=False
use_random_templates=False 
specific_template=Template_6.tmpl

print_ast_to_console=False
save_ast=False
open_saved_ast_images=True #This only works when the save_ast is True
save_ast_as_json=False

print_template_to_console=False
print_rendered_template_to_console=True

format_generated_code=True
static_analysis_of_generate_code=True

print_array_data=True #Make it false if the generated array data needn't to be printed

[TEMPLATE_GENERATION]
number_of_functions=5
number_of_other_elements=5

#TODO::Add more configurability like specifying... if, while statements

[GENERAL]
debug_mode=False

[FEEDBACK_MANAGER]
server_host=0.0.0.0
server_port=5002
destination_url=http://localhost:5001/compile



